services:
  mysql:
    container_name: unit-1-mysql
    image: mysql:8.4
    env_file:
      - ./env/mysql.env

  server:
    container_name: unit-1-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./env/server.env
    depends_on:
      - mysql

  client:
    container_name: unit-1-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - server
